import 'package:flutter/material.dart';

Lang strings = Lang();

class Lang {
  var direction = TextDirection.ltr;
  var locale = "en";

  Map<int, String> langEng = {
    0: "",
    1: "SIGN IN",
    2: "Enter your Phone number",
    3: "Enter your Password",
    4: "Enter your Email",
    5: "Remember me",
    6: "Forgot password?",
    7: "I agree with",
    8: "Terms & Conditions",
    9: "Sign Up",
    10: "Sign In",
    11: "or continue with",
    12: "Please Enter Email",
    13: "Please Enter Password",
    14: "SIGN UP",
    15: "Confirm Password",
    16: "Enter your Name",
    17: "Next",
    18: "Please enter Your registered email so that we can help you to recover Your password.",
    19: "Home",
    20: "Favorites",
    21: "Cart",
    22: "Notify",
    23: "Menu",
    24: "Search",
    25: "Categories",
    26: "View all",
    27: "Top Favorites",
    28: "Top Trends",
    29: "Providers",
    30: "Not available Now",
    31: "Service",
    32: "Provider",
    33: "Search in favorites",
    34: "Filter",
    35: "Apply Filter",
    36: "Reset Filter",
    37: "Sort by",
    38: "Ascending (A-Z)",
    39: "Descending (Z-A)",
    40: "Filter by",
    41: "Currently available services",
    42: "Discounted services",
    43: "Price",
    44: "Rating",
    45: "Profile",
    46: "Privacy Policy",
    47: "About Us",
    48: "Dark Mode",
    49: "My Address",
    50: "Language",
    51: "Sign Out",
    52: "Select Language",
    53: "SUBMIT",
    54: "Please Enter Email",
    55: "Please enter password",
    56: "Passwords are not equal",
    57: "Email are wrong",
    58: "Set Location",
    59: "Find services near your",
    60: "By allowing location access, you can search for services and providers near your.",
    61: "Use currents location",
    62: "Set from map",
    63: "Pick the Address",
    64: "This address",
    65: "Please enter address",
    66: "Add the location",
    67: "Label as",
    68: "Home",
    69: "Office",
    70: "Other",
    71: "Delivery Address",
    72: "Contact name",
    73: "Contact phone number",
    74: "Save location",
    75: "Enter Delivery Address",
    76: "Enter Contact phone number",
    77: "Enter Contact name",
    78: "My Address",
    79: "Address not found",
    80: "Add address",
    81: "Location",
    82: "Booking",
    83: "Services not found",
    84: "Providers not found",
    85: "You are not authorized",
    86: "Not found ...",
    87: "Notifications",
    88: "Today",
    89: "Running",
    90: "History",
    91: "My Booking",
    92: "Quantity",
    93: "Addons",
    94: "Add to cart",
    95: "Total amount",
    96: "Monday",
    97: "Tuesday",
    98: "Wednesday",
    99: "Thursday",
    100: "Friday",
    101: "Saturday",
    102: "Sunday",
    103: "Weekend",
    104: "Galleries",
    105: "Reviews & Ratings",
    106: "My Profile",
    107: "Everything about you",
    108: "Name",
    109: "Enter your name",
    110: "Email",
    111: "main@gmail.com",
    112: "Phone number",
    113: "+69091234566789",
    114: "SAVE",
    115: "Change password",
    116: "New password",
    117: "123456",
    118: "Confirm New password",
    119: "CHANGE PASSWORD",
    120: "Enter Password",
    121: "Enter Confirm Password",
    122: "Passwords are not equal",
    123: "Please Enter name",
    124: "Change profile",
    125: "Change avatar",
    126: "From Library",
    127: "From Camera",
    128: "Total booking",
    129: "Total spent",
    130: "Get favorite service",
    131: "Select your location to see the wide range providers and booking your desired service.",
    132: "Easy payment",
    133: "Booking service with COD payment or pay by safer and faster payment gateways.",
    134: "Fast work",
    135: "Hundreds of service man are waiting for you booking.",
    136: "Skip",
    137: "GET STARTED",
    138: "Chat",
    139: "Write your message ...",
    140: "Pending",
    141: "Track booking",
    142: "Booking tracking",
    143: "Booking not found",
    144: "Booking details",
    145: "Order ID:",
    146: "Payment",
    147: "Cash payment",
    148: "Status",
    149: "Accept",
    150: "Addons:",
    151: "Quantity:",
    152: "Item price",
    153: "Subtotal",
    154: "Discount",
    155: "VAT/TAX",
    156: "Total amount",
    157: "Cancel booking",
    158: "My Cart",
    159: "Category",
    160: "Your cart in empty",
    161: "Proceed to checkout",
    162: "Checkout",
    163: "Confirm order",
    164: "CODE123",
    165: "Apply",
    166: "Choose payment method",
    167: "Pay your payment after getting service",
    168: "Digital payment",
    169: "Faster and safer way to send money",
    170: "Additional note",
    171: "Back to Home",
    172: "You Place to Booking Successfully",
    173:
        "Your Booking is placed successfully. We start our work process and you will receive your service soon.",
  };

  // Map<String, dynamic>? defaultLang;
  Map<int, String>? defaultLang;

  setLang(Map<int, String> def, String locale, BuildContext context, TextDirection direction) {
    defaultLang = def;
    locale = locale;
    direction = direction;
    // Provider.of<LanguageChangeNotifierProvider>(context, listen: false).changeLocale(locale);
  }

  String get(int id) {
    // return langEng[id] == null ? "" : langEng[id]!;

    if (defaultLang == null) {
      return langEng[id] == null ? "" : langEng[id]!;
    } else {
      // print("strings get id=$id defaultLang=$defaultLang");
      // var t = defaultLang![id.toString()];
      var t = defaultLang![id];
      return t ?? (langEng[id] == null ? "" : langEng[id]!);
    }
  }
}

setLang(String locale, BuildContext context) {
  for (var item in langData) {
    if (locale == item.locale) {
      strings.setLang(item.data, locale, context, item.direction);
    }
  }
}

List<LangData> langData = [
  LangData(
      name: "English",
      engName: "English",
      image: "assets/usa.png",
      current: false,
      locale: "en",
      direction: TextDirection.ltr,
      data: strings.langEng),
  LangData(
      name: "عربى",
      engName: "Arabic",
      image: "assets/arabic.png",
      current: false,
      locale: "ar",
      direction: TextDirection.rtl,
      data: langAr),
  LangData(
      name: "हिंदी",
      engName: "Hindy",
      image: "assets/usa.jpg",
      current: false,
      locale: "ru",
      direction: TextDirection.ltr,
      data: langHi),
];

class LangData {
  String name;
  String engName;
  String image;
  bool current;
  String locale;
  TextDirection direction;
  Map<int, String> data;

  LangData(
      {required this.name,
      required this.engName,
      required this.image,
      required this.current,
      required this.locale,
      required this.direction,
      required this.data});
}

Map<int, String> langAr = {
  0: "",
  1: "تسجيل الدخول",
  2: "أدخل رقم هاتفك",
  3: "أدخل كلمة المرور الخاصة بك",
  4: "أدخل بريدك الإلكتروني",
  5: "تذكرني",
  6: "هل نسيت كلمة المرور؟",
  7: "أوافق",
  8: "الشروط والأحكام",
  9: "تسجيل",
  10: "تسجيل الدخول",
  11: "أو متابعة",
  12: "الرجاء إدخال البريد الإلكتروني",
  13: "الرجاء إدخال كلمة المرور",
  14: "الاشتراك",
  15: "تأكيد كلمة المرور",
  16: "أدخل اسمك",
  17: "التالي",
  18: "الرجاء إدخال بريدك الإلكتروني المسجل حتى نتمكن من مساعدتك في استعادة كلمة المرور الخاصة بك.",
  19: "الصفحة الرئيسية",
  20: "المفضلة",
  21: "عربة التسوق",
  22: "إعلام",
  23: "القائمة",
  24: "بحث",
  25: "الفئات",
  26: "عرض الكل",
  27: "أفضل المفضلات",
  28: "أهم الاتجاهات",
  29: "الموفرون",
  30: "غير متوفر الآن",
  31: "الخدمة",
  32: "مقدم الخدمة",
  33: "البحث في المفضلة",
  34: "تصفية",
  35: "تطبيق عامل التصفية",
  36: "إعادة تعيين عامل التصفية",
  37: "فرز حسب",
  38: "تصاعدي (أ-ي)",
  39: "تنازلي (ي - أ)",
  40: "تصفية حسب",
  41: "الخدمات المتاحة حاليًا",
  42: "الخدمات المخفضة",
  43: "السعر",
  44: "التصنيف",
  45: "الملف الشخصي",
  46: "سياسة الخصوصية",
  47: "من نحن",
  48: "الوضع الداكن",
  49: "عنواني",
  50: "اللغة",
  51: "تسجيل الخروج",
  52: "تحديد اللغة",
  53: "إرسال",
  54: "الرجاء إدخال البريد الإلكتروني",
  55: "الرجاء إدخال كلمة المرور",
  56: "كلمات المرور غير متساوية",
  57: "البريد الإلكتروني خاطئ",
  58: "تعيين الموقع",
  59: "البحث عن خدمات بالقرب منك",
  60: "بالسماح بالوصول إلى الموقع , يمكنك البحث عن الخدمات والموفرين بالقرب منك.",
  61: "استخدام موقع التيارات",
  62: "تعيين من الخريطة",
  63: "اختر العنوان",
  64: "هذا العنوان",
  65: "الرجاء إدخال العنوان",
  66: "أضف الموقع",
  67: "تسمية كـ",
  68: "الصفحة الرئيسية",
  69: "مكتب",
  70: "أخرى",
  71: "عنوان التسليم",
  72: "اسم جهة الاتصال",
  73: "رقم هاتف جهة الاتصال",
  74: "حفظ الموقع",
  75: "أدخل عنوان التسليم",
  76: "أدخل رقم هاتف جهة الاتصال",
  77: "أدخل اسم جهة الاتصال",
  78: "عنواني",
  79: "لم يتم العثور على العنوان",
  80: "إضافة عنوان",
  81: "الموقع",
  82: "الحجز",
  83: "لم يتم العثور على الخدمات",
  84: "لم يتم العثور على مقدمي",
  85: "غير مصرح لك",
  86: "غير موجود ...",
  87: "الإخطارات",
  88: "اليوم",
  89: "قيد التشغيل",
  90: "التاريخ",
  91: "حجزي",
  92: "الكمية",
  93: "الإضافات",
  94: "إضافة إلى عربة التسوق",
  95: "المبلغ الإجمالي",
  96: "الاثنين",
  97: "الثلاثاء",
  98: "الأربعاء",
  99: "الخميس",
  100: "الجمعة",
  101: "السبت",
  102: "الأحد",
  103: "عطلة نهاية الأسبوع",
  104: "المعارض",
  105: "التعليقات والتقييمات",
  106: "ملفي الشخصي",
  107: "كل شيء عنك",
  108: "الاسم",
  109: "أدخل اسمك",
  110: "البريد الإلكتروني",
  111: "main@gmail.com",
  112: "رقم الهاتف",
  113: "+69091234566789",
  114: "حفظ",
  115: "تغيير كلمة المرور",
  116: "كلمة مرور جديدة",
  117: "123456",
  118: "تأكيد كلمة المرور الجديدة",
  119: "تغيير كلمة المرور",
  120: "أدخل كلمة المرور",
  121: "أدخل تأكيد كلمة المرور",
  122: "كلمات المرور غير متساوية",
  123: "الرجاء إدخال الاسم",
  124: "تغيير ملف التعريف",
  125: "تغيير الصورة الرمزية",
  126: "من المكتبة",
  127: "من الكاميرا",
  128: "إجمالي الحجز",
  129: "إجمالي الإنفاق",
  130: "الحصول على الخدمة المفضلة",
  131: "حدد موقعك لرؤية مزودي النطاق الواسع وحجز الخدمة التي تريدها.",
  132: "دفع سهل",
  133: "خدمة الحجز بدفع COD أو الدفع عن طريق بوابات دفع أكثر أمانًا وأسرع.",
  134: "العمل السريع",
  135: "المئات من رجال الخدمة بانتظارك الحجز",
  136: "تخطي",
  137: "ابدأ",
  138: "دردشة",
  139: "اكتب رسالتك ...",
  140: "معلق",
  141: "تتبع الحجز",
  142: "تتبع الحجز",
  143: "الحجز غير موجود",
  144: "تفاصيل الحجز",
  145: "معرف الطلب:",
  146: "الدفع",
  147: "الدفع النقدي",
  148: "الحالة",
  149: "قبول",
  150: "الإضافات:",
  151: "الكمية:",
  152: "سعر العنصر",
  153: "المجموع الفرعي",
  154: "خصم",
  155: "ضريبة القيمة المضافة / الضرائب",
  156: "المبلغ الإجمالي",
  157: "إلغاء الحجز",
  158: "عربتي",
  159: "الفئة",
  160: "عربة التسوق فارغة",
  161: "تابع الدفع",
  162: "الخروج",
  163: "تأكيد الطلب",
  164: "CODE123",
  165: "تطبيق",
  166: "اختر طريقة الدفع",
  167: "ادفع دفعتك بعد الحصول على الخدمة",
  168: "الدفع الرقمي",
  169: "طريقة أسرع وأكثر أمانًا لإرسال الأموال",
  170: "ملاحظة إضافية",
  171: "العودة إلى المنزل",
  172: "لقد نجحت في الحجز",
  173: "تم حجزك بنجاح. نبدأ عملية عملنا وستتلقى خدمتك قريبًا.",
};

Map<int, String> langHi = {
  0: "",
  1: "साइन इन",
  2: "अपना फोन नंबर दर्ज करें",
  3: "अपना पासवर्ड दर्ज करें",
  4: "अपना ईमेल दर्ज करें",
  5: "मुझे याद रखें",
  6: "पासवर्ड भूल गए?",
  7: "मैं इससे सहमत हूं",
  8: "नियम और शर्तें",
  9: "साइन अप",
  10: "साइन इन करें",
  11: "या जारी रखें",
  12: "कृपया ईमेल दर्ज करें",
  13: "कृपया पासवर्ड दर्ज करें",
  14: "साइन अप",
  15: "पासवर्ड की पुष्टि करें",
  16: "अपना नाम दर्ज करें",
  17: "अगला",
  18: "कृपया अपना पंजीकृत ईमेल दर्ज करें ताकि हम आपका पासवर्ड पुनर्प्राप्त करने में आपकी सहायता कर सकें।",
  19: "होम",
  20: "पसंदीदा",
  21: "गाड़ी",
  22: "सूचित करें",
  23: "मेनू",
  24: "खोज",
  25: "श्रेणियाँ",
  26: "सभी देखें",
  27: "शीर्ष पसंदीदा",
  28: "शीर्ष रुझान",
  29: "प्रदाता",
  30: "अभी उपलब्ध नहीं है",
  31: "सेवा",
  32: "प्रदाता",
  33: "पसंदीदा में खोजें",
  34: "फ़िल्टर",
  35: "फ़िल्टर लागू करें",
  36: "फ़िल्टर रीसेट करें",
  37: "क्रमबद्ध करें",
  38: "आरोही (ए-जेड)",
  39: "अवरोही (जेड-ए)",
  40: "इसके अनुसार फ़िल्टर करें",
  41: "वर्तमान में उपलब्ध सेवाएं",
  42: "छूट वाली सेवाएं",
  43: "कीमत",
  44: "रेटिंग",
  45: "प्रोफाइल",
  46: "गोपनीयता नीति",
  47: "हमारे बारे में",
  48: "डार्क मोड",
  49: "मेरा पता",
  50: "भाषा",
  51: "साइन आउट",
  52: "भाषा चुनें",
  53: "सबमिट करें",
  54: "कृपया ईमेल दर्ज करें",
  55: "कृपया पासवर्ड दर्ज करें",
  56: "पासवर्ड समान नहीं हैं",
  57: "ईमेल गलत हैं",
  58: "स्थान निर्धारित करें",
  59: "अपने आस-पास की सेवाओं का पता लगाएं",
  60: "लोकेशन एक्सेस की अनुमति देकर, आप अपने आस-पास की सेवाओं और प्रदाताओं की खोज कर सकते हैं।",
  61: "करंट लोकेशन का उपयोग करें",
  62: "मानचित्र से सेट करें",
  63: "पता चुनें",
  64: "यह पता",
  65: "कृपया पता दर्ज करें",
  66: "स्थान जोड़ें",
  67: "लेबल के रूप में",
  68: "होम",
  69: "कार्यालय",
  70: "अन्य",
  71: "डिलीवरी पता",
  72: "संपर्क नाम",
  73: "फोन नंबर से संपर्क करें",
  74: "स्थान सहेजें",
  75: "डिलीवरी पता दर्ज करें",
  76: "संपर्क फोन नंबर दर्ज करें",
  77: "संपर्क नाम दर्ज करें",
  78: "मेरा पता",
  79: "पता नहीं मिला",
  80: "पता जोड़ें",
  81: "स्थान",
  82: "बुकिंग",
  83: "सेवाएँ नहीं मिलीं",
  84: "प्रदाता नहीं मिले",
  85: "आप अधिकृत नहीं हैं",
  86: "नहीं मिला ...",
  87: "सूचनाएं",
  88: "आज",
  89: "चल रहा है",
  90: "इतिहास",
  91: "मेरी बुकिंग",
  92: "मात्रा",
  93: "एडॉन्स",
  94: "कार्ट में जोड़ें",
  95: "कुल राशि",
  96: "सोमवार",
  97: "मंगलवार",
  98: "बुधवार",
  99: "गुरुवार",
  100: "शुक्रवार",
  101: "शनिवार",
  102: "रविवार",
  103: "सप्ताहांत",
  104: "दीर्घाएँ",
  105: "समीक्षा और रेटिंग",
  106: "माई प्रोफाइल",
  107: "आपके बारे में सब कुछ",
  108: "नाम",
  109: "अपना नाम दर्ज करें",
  110: "ईमेल",
  111: "main@gmail.com",
  112: "फोन नंबर",
  113: "+६९०९१२३४५६६७८९",
  114: "बचाओ",
  115: "पासवर्ड बदलें",
  116: "नया पासवर्ड",
  117: "123456",
  118: "नए पासवर्ड की पुष्टि करें",
  119: "पासवर्ड बदलें",
  120: "पासवर्ड दर्ज करें",
  121: "पासवर्ड की पुष्टि दर्ज करें",
  122: "पासवर्ड समान नहीं हैं",
  123: "कृपया नाम दर्ज करें",
  124: "प्रोफाइल बदलें",
  125: "अवतार बदलें",
  126: "लाइब्रेरी से",
  127: "कैमरा से",
  128: "कुल बुकिंग",
  129: "कुल खर्च",
  130: "पसंदीदा सेवा प्राप्त करें",
  131:
      "विस्तृत श्रेणी प्रदाताओं को देखने और अपनी वांछित सेवा की बुकिंग के लिए अपने स्थान का चयन करें।",
  132: "आसान भुगतान",
  133: "सीओडी भुगतान के साथ बुकिंग सेवा या सुरक्षित और तेज भुगतान गेटवे द्वारा भुगतान।",
  134: "तेजी से काम",
  135: "सैकड़ों सर्विस मैन आपकी बुकिंग का इंतजार कर रहे हैं।",
  136: "छोड़ें",
  137: "आरंभ करें",
  138: "चैट",
  139: "अपना संदेश लिखें ...",
  140: "लंबित",
  141: "ट्रैक बुकिंग",
  142: "बुकिंग ट्रैकिंग",
  143: "बुकिंग नहीं मिली",
  144: "बुकिंग विवरण",
  145: "ऑर्डर आईडी:",
  146: "भुगतान",
  147: "नकद भुगतान",
  148: "स्थिति",
  149: "स्वीकार करें",
  150: "एडॉन्स:",
  151: "मात्रा:",
  152: "आइटम की कीमत",
  153: "सबटोटल",
  154: "छूट",
  155: "वैट/टैक्स",
  156: "कुल राशि",
  157: "बुकिंग रद्द करें",
  158: "माई कार्ट",
  159: "श्रेणी",
  160: "आपकी गाड़ी खाली है",
  161: "चेकआउट के लिए आगे बढ़ें",
  162: "चेकआउट",
  163: "आदेश की पुष्टि करें",
  164: "CODE123",
  165: "लागू करें",
  166: "भुगतान विधि चुनें",
  167: "सेवा प्राप्त करने के बाद अपना भुगतान करें",
  168: "डिजिटल भुगतान",
  169: "पैसे भेजने का तेज़ और सुरक्षित तरीका",
  170: "अतिरिक्त नोट",
  171: "बैक टू होम",
  172: "आप सफलतापूर्वक बुकिंग के लिए स्थान",
  173:
      "आपकी बुकिंग सफलतापूर्वक हो गई है। हम अपनी कार्य प्रक्रिया शुरू करते हैं और आप जल्द ही अपनी सेवा प्राप्त करेंगे।",
};
